### ISSUE TITLE
GiBs should be MiBs during kcctl deploy downloading step

### ISSUE THREAD

**Issue by ghost** [kubeclipper-labs/kubectl#1]
<img width="1679" alt="WeChatWorkScreenshot_17bafcfc-ceca-4553-b0bd-dc088ab95a75" src="https://user-images.githubusercontent.com/2706151/206666958-8f457b6a-fafb-4295-8907-f382eab8d99c.png">

**Comment by lixd** [comment]
/close 
fixed by https://github.com/kubeclipper/kubeclipper/pull/529
